### ISSUE TITLE
Feature: command hook

### ISSUE THREAD

**Issue by NWYLZW** [linearite/linearite#3]
# Command Hook

```yaml
builder: esbuild
matrix:
    *:
        after:
            build:
                - rm -rf dist
                - test
        before:
            build: build index.d.ts
    packages/cli:
        after:
            build: insert #!/bin/node
        before:
            build: remove #!/bin/node
```

## 不会做的事情

* hook 的 hook，不可能出现 after-after，也不会有 before-before

## 能做的事情

* 并行语法与顺序语法，目前应该是一个顺序语法
